export const LOGIN_CLICK_1 = "LOGIN_CLICK_1";
export const LOGIN_CLICK_2 = "LOGIN_CLICK_2";
export const REGISTER_CLICK_1 = "REGISTER_CLICK_1";
export const REGISTER_CLICK_2 = "REGISTER_CLICK_2";
export const PANEL_SHOW_BUTTON = "PANEL_SHOW_BUTTON";
export const PANEL_HIDE_BUTTON = "PANEL_HIDE_BUTTON";

export const CONFIRM_EMAIL = "CONFIRM_EMAIL";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const CHANGE_PASSWORD_FAILED = "CHANGE_PASSWORD_FAILED";
export const SET_CURRENT_USER_AUTHEN = "SET_CURRENT_USER_AUTHEN";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const DISABLE_ALL = "DISABLE_ALL";

export const SEARCH = "SEARCH";
export const SEARCH_RELATIONSHIP = "SEARCH_RELATIONSHIP";
