export const LOGIN_CLICK_1 = "LOGIN_CLICK_1";
export const LOGIN_CLICK_2 = "LOGIN_CLICK_2";
export const REGISTER_CLICK_1 = "REGISTER_CLICK_1";
export const REGISTER_CLICK_2 = "REGISTER_CLICK_2";
export const PANEL_SHOW_BUTTON = "PANEL_SHOW_BUTTON";
export const PANEL_HIDE_BUTTON = "PANEL_HIDE_BUTTON";
